title: Paul Laffitte
theme: minima
email: paul.laffitte@epitech.eu
github_username: paullaffitte

# markdown: kramdown
# plugins:
#   - jekyll-feed

destination: _site

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
